// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzaAadetggLG7qze3ZhozqUj7u04r4L7g',
    appId: '1:526068352011:web:6d59cc45d55970e464f30e',
    messagingSenderId: '526068352011',
    projectId: 'craftedcreations-c7e09',
    authDomain: 'craftedcreations-c7e09.firebaseapp.com',
    storageBucket: 'craftedcreations-c7e09.appspot.com',
    measurementId: 'G-K2QN47B58V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-qv0dE-WTTOW0XOkCg_t3rkNUrY8Dz70',
    appId: '1:526068352011:android:3502cbce522607e764f30e',
    messagingSenderId: '526068352011',
    projectId: 'craftedcreations-c7e09',
    storageBucket: 'craftedcreations-c7e09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwjIMY6KP9nLcidTfxn7DMj15ez19dmKs',
    appId: '1:526068352011:ios:aea855aad84e3b5d64f30e',
    messagingSenderId: '526068352011',
    projectId: 'craftedcreations-c7e09',
    storageBucket: 'craftedcreations-c7e09.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwjIMY6KP9nLcidTfxn7DMj15ez19dmKs',
    appId: '1:526068352011:ios:9c9ddb52fee1b16c64f30e',
    messagingSenderId: '526068352011',
    projectId: 'craftedcreations-c7e09',
    storageBucket: 'craftedcreations-c7e09.appspot.com',
    iosBundleId: 'com.example.portfolio.RunnerTests',
  );
}
