import 'package:flutter/material.dart';
import 'package:flutter_animator/flutter_animator.dart';

class ProjectsScreen extends StatelessWidget {
  const ProjectsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        automaticallyImplyLeading: false,
        title: const Text(
          'My Projects',
          style: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.bold,
              color: Colors.white),
        ),
        backgroundColor: const Color(0xFF6A1B9A),  // Purple color for consistency
      ),
      body: ListView(
        padding: const EdgeInsets.all(8.0),  // Added padding around the list
        children: <Widget>[
          FadeInUp(
            child: const ProjectWidget(
              imageUrl: 'assets/images/builder.webp',
              title: 'Application Builder',
              duration: '9 Months',
              description:
              'Developed a low-code tool for building end-to-end mobile/web applications using Flutter and NodeJS.',
            ),
          ),
          const SizedBox(height: 10),
          FadeInLeft(
            child: const ProjectWidget(
              imageUrl: 'assets/images/aqsus.webp',
              title: 'Aqsus',
              duration: '3 Months',
              description:
              'Contributed to a Web 3 based cross-blockchain marketplace built on the Near blockchain.',
            ),
          ),
          const SizedBox(height: 10),
          FadeInRight(
            child: const ProjectWidget(
              imageUrl: 'assets/images/banking.webp',
              title: 'Banking System',
              duration: '6 Months',
              description:
              'Involved in the development of a banking app focusing on KYC, managing dashboards, and setting card limits.',
            ),
          ),
          const SizedBox(height: 10),
          FadeInDownBig(
            child: const ProjectWidget(
              imageUrl: 'assets/images/kidney.webp',
              title: 'Kidney Stone Detection using Deep Learning',
              duration: '2 Months',
              description:
              'An academic project focusing on developing a deep learning model for detecting and classifying kidney stones in medical images.',
            ),
          ),
          const SizedBox(height: 10),
          const ProjectWidget(
            imageUrl: 'assets/images/diamonds.webp',
            title: 'Diamond Price Prediction using Machine Learning',
            duration: '2 Months',
            description:
            'This project aimed to develop a machine learning model for predicting diamond prices based on various features.',
          ),
          const SizedBox(height: 10),
          const ProjectWidget(
            imageUrl: 'assets/images/student.webp',
            title: 'Smart Attendance System',
            duration: '2 Months',
            description:
            'A project involving the development of a system to track, maintain, and manage data generated by a college, including student grades and activities.',
          ),
        ],
      ),
    );
  }
}

class ProjectWidget extends StatelessWidget {
  final String? title;
  final String? duration;
  final String? description;
  final Color? backgroundColor;
  final String? imageUrl;

  const ProjectWidget({
    super.key,
    this.title,
    this.duration,
    this.description,
    this.imageUrl,
    this.backgroundColor,
  });

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 4,
      shadowColor: const Color(0xFF6A1B9A), // Purple shadow for consistency
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(12),
      ),
      margin: const EdgeInsets.symmetric(vertical: 8), // Margin between cards
      color: backgroundColor ?? Colors.white,
      child: Padding(
        padding: const EdgeInsets.all(16.0), // Padding around card content
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            if (imageUrl != null)
              ClipRRect(
                borderRadius: BorderRadius.circular(8), // Rounded corners for image
                child: Image.asset(
                  imageUrl!,
                  width: double.infinity,
                  height: 150, // Limit the height to avoid stretching
                  fit: BoxFit.contain, // Maintain the aspect ratio
                ),
              ),
            const SizedBox(height: 10),
            Row(
              children: <Widget>[
                Expanded(
                  child: Text(
                    title!,
                    style: const TextStyle(
                        fontSize: 18, fontWeight: FontWeight.bold),
                  ),
                ),
                Text(
                  duration!,
                  style: const TextStyle(
                      fontSize: 16, fontStyle: FontStyle.italic, color: Colors.grey),
                ),
              ],
            ),
            const SizedBox(height: 10),
            Text(
              description!,
              style: const TextStyle(fontSize: 16, color: Colors.black),
            ),
          ],
        ),
      ),
    );
  }
}
