import 'package:flutter/material.dart';
import 'package:flutter_animator/flutter_animator.dart';

class ProjectsScreen extends StatelessWidget {
  const ProjectsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          'My Projects',
          style: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.bold,
              color: Colors.deepPurple),
        ),
      ),
      body: ListView(
        children: <Widget>[
          FadeInUp(
            child: const ProjectWidget(
              imageUrl: 'assets/images/builder.webp',
              title: 'Application Builder',
              duration: '9 Months',
              description:
                  'Developed a low-code tool for building end-to-end mobile/web applications using Flutter and NodeJS.',
            ),
          ),
          const SizedBox(height: 10),
          FadeInLeft(
            child: const ProjectWidget(
              imageUrl: 'assets/images/aqsus.webp',
              title: 'Aqsus',
              duration: '3 Months',
              description:
                  'Contributed to a Web 3 based cross-blockchain marketplace built on the Near blockchain.',
            ),
          ),
          const SizedBox(height: 10),
          FadeInRight(
            child: const ProjectWidget(
              imageUrl: 'assets/images/banking.webp',
              title: 'Banking System',
              duration: '6 Months',
              description:
                  'Involved in the development of a banking app focusing on KYC, managing dashboards, and setting card limits.',
            ),
          ),
          const SizedBox(height: 10),
          FadeInDownBig(
            child: const ProjectWidget(
              imageUrl: 'assets/images/kidney.webp',
              title: 'Kidney Stone Detection using Deep Learning',
              duration: '2 Months',
              description:
                  'An academic project focusing on developing a deep learning model for detecting and classifying kidney stones in medical images.',
            ),
          ),
          const SizedBox(height: 10),
          const ProjectWidget(
            imageUrl: 'assets/images/diamonds.webp',
            title: 'Diamond Price Prediction using Machine Learning',
            duration: '2 Months',
            description:
                'This project aimed to develop a machine learning model for predicting diamond prices based on various features.',
          ),
          const SizedBox(height: 10),
          const ProjectWidget(
            imageUrl: 'assets/images/student.webp',
            title: 'Smart Attendance System',
            duration: '2 Months',
            description:
                'A project involving the development of a system to track, maintain, and manage data generated by a college, including student grades and activities.',
          ),
        ],
      ),
    );
  }
}

class ProjectWidget extends StatelessWidget {
  final String? title;
  final String? duration;
  final String? description;
  final Color? backgroundColor;
  final String? imageUrl;

  const ProjectWidget(
      {super.key,
      this.title,
      this.duration,
      this.description,
      this.imageUrl,
      this.backgroundColor});

  @override
  Widget build(BuildContext context) {
    return Card(
      color: backgroundColor,
      child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            if (imageUrl != null)
              Image.asset(imageUrl!, width: double.infinity, height: 100),
            const SizedBox(height: 8),
            Row(children: <Widget>[
              SizedBox(
                width: MediaQuery.of(context).size.width * 0.7,
                child: Text(
                  title!,
                  softWrap: true,
                  style: const TextStyle(
                      fontSize: 18, fontWeight: FontWeight.bold),
                ),
              ),
              const Spacer(),
              Text(
                duration!,
                style:
                    const TextStyle(fontSize: 16, fontStyle: FontStyle.italic),
              ),
            ]),
            const SizedBox(height: 8),
            Text(
              description!,
              style: const TextStyle(fontSize: 16),
            ),
          ],
        ),
      ),
    );
  }
}
